apiVersion: 1
contactPoints:
  - orgId: 1
    name: Telegram Alert
    receivers:
      - uid: telegram-receiver-1
        type: telegram
        settings:
          bottoken: "8674034190:AAE4a9EsNsaozYtYTbvFIqJ7FerxMwmWb3g"
          chatid: "8722599561"
policies:
  - orgId: 1
    receiver: "Telegram Alert"