apiVersion: 1
groups:
  - orgId: 1
    name: 1m
    folder: Linux_System_Alerts
    interval: 1m
    rules:
      - uid: cflprhe7141z4a
        title: CPU 사용률 80% 초과
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: bfkbzvtd8ke0wd
            model:
              editorMode: code
              expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            queryType: expression
            datasourceUid: __expr__
            model:
              conditions:
                  - evaluator:
                      params:
                          - 80
                      type: gt
                    operator:
                      type: and
                    query:
                      params:
                          - C
                    reducer:
                      params: []
                      type: last
                    type: query
              datasource:
                  type: __expr__
                  uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          description: 서버의 연산 부하가 높습니다. 현재 프로세스 점검이 필요합니다.
        isPaused: false
        notification_settings:
          receiver: Telegram Alert
      - uid: bflprk5n0l6gwa
        title: 메모리 점유율 80% 초과
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: bfkbzvtd8ke0wd
            model:
              editorMode: code
              expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            queryType: expression
            datasourceUid: __expr__
            model:
              conditions:
                  - evaluator:
                      params:
                          - 80
                      type: gt
                    operator:
                      type: and
                    query:
                      params:
                          - C
                    reducer:
                      params: []
                      type: last
                    type: query
              datasource:
                  type: __expr__
                  uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          description: 메모리 잔량이 부족 합니다.
        isPaused: false
        notification_settings:
          receiver: Telegram Alert
      - uid: cflprm5pnm8lcb
        title: 디스크 용량 90% 돌파
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: bfkbzvtd8ke0wd
            model:
              editorMode: code
              expr: (1 - (node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})) * 100
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            queryType: expression
            datasourceUid: __expr__
            model:
              conditions:
                  - evaluator:
                      params:
                          - 90
                      type: gt
                    operator:
                      type: and
                    query:
                      params:
                          - C
                    reducer:
                      params: []
                      type: last
                    type: query
              datasource:
                  type: __expr__
                  uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          description: 서버 저장 공간이 거의 꽉 찼습니다.
        isPaused: false
        notification_settings:
          receiver: Telegram Alert
      - uid: dflprnoa3ri80c
        title: 네트워크 트래픽 급증
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: bfkbzvtd8ke0wd
            model:
              editorMode: code
              expr: rate(node_network_receive_bytes_total[1m]) * 8 / 1024 / 1024
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            queryType: expression
            datasourceUid: __expr__
            model:
              conditions:
                  - evaluator:
                      params:
                          - 100
                      type: gt
                    operator:
                      type: and
                    query:
                      params:
                          - C
                    reducer:
                      params: []
                      type: last
                    type: query
              datasource:
                  type: __expr__
                  uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          description: 초당 유입되는 네트워크 데이터가 설정값100M을 넘었습니다.
        isPaused: false
        notification_settings:
          receiver: Telegram Alert