---
# Prometheus 설치 (collection)
- name: install prometheus
  include_role:
    name: prometheus.prometheus.prometheus
  vars:
    prometheus_version: "2.47.0"

- name: "플랫폼 정보 수집"
  ansible.builtin.setup:
    gather_subset: min

- name: "필수 패키지 설치(Debian 계열)"
  when: ansible_facts['os_family'] == "Debian"
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - wget
      - gnupg2
    state: present
    update_cache: yes

- name: Grafana GPG 키 다운로드
  get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /tmp/grafana.key   # ✅ 여기 중요
    mode: '0644'

- name: 기존 keyring 제거 (중요🔥)
  file:
    path: /usr/share/keyrings/grafana.gpg
    state: absent

- name: Grafana GPG key 변환 (dearmor)
  command: gpg --dearmor -o /usr/share/keyrings/grafana.gpg /tmp/grafana.key
  
- name: Grafana repo 추가
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/grafana.gpg] https://apt.grafana.com stable main"
    state: present

# - name: "Grafana GPG 키 등록 (Debian 계열)"
#   when: ansible_facts['os_family'] == "Debian"
#   ansible.builtin.apt_key:
#     url: https://packages.grafana.com/gpg.key
#     state: present

# - name: "Grafana APT 저장소 추가 (Debian 계열)"
#   when: ansible_facts['os_family'] == "Debian"
#   ansible.builtin.apt_repository:
#     repo: "deb https://packages.grafana.com/oss/deb stable main"
#     state: present
#     filename: grafana

- name: "Grafana 설치 (Debian 계열)"
  when: ansible_facts['os_family'] == "Debian"
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: yes

- name: "Grafana 서비스 시작 및 부팅 시 자동실행"
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: yes

# - name: install alertmanager
#   include_role:
#     name: cloudalchemy.alertmanager