---
- name: install node exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/latest/download/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: extract
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/
    remote_src: yes

- name: copy binary
  copy:
    src: /opt/node_exporter-*/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    mode: 0755

- name: create service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: start service
  systemd:
    name: node_exporter
    state: started
    enabled: yes